In [37]:
import pandas as pd
names = ['id', 'title', 'year', 'rating', 'votes', 'length', 'genre']
data = pd.read_csv('imdb_top_10000.txt', sep='\t', names=names, index_col=0)

# First clean the title by slicing the title field
data['sliced title'] = data['title'].str[:-7]

# We could do it this way though
data['split title'] = data['title'].str.split(' \(').str[0]

# get the length challenge!
data['astype int length'] = data['length'].str.split(' ').str[0].astype(int)
data['to_numeric length'] = pd.to_numeric(data['length'].str.split(' ').str[0])

# genres
data['genre list'] = data['genre'].str.split('|')
data

,title,year,rating,votes,length,genre,sliced title,split title,astype int length,to_numeric length,genre list
id,,,,,,,,,,,
tt0111161,The Shawshank Redemption (1994),1994,9.2,619479,142 mins.,Crime|Drama,The Shawshank Redemption,The Shawshank Redemption,142,142,"[Crime, Drama]"
tt0110912,Pulp Fiction (1994),1994,9.0,490065,154 mins.,Crime|Thriller,Pulp Fiction,Pulp Fiction,154,154,"[Crime, Thriller]"
tt0137523,Fight Club (1999),1999,8.8,458173,139 mins.,Drama|Mystery|Thriller,Fight Club,Fight Club,139,139,"[Drama, Mystery, Thriller]"
tt0133093,The Matrix (1999),1999,8.7,448114,136 mins.,Action|Adventure|Sci-Fi,The Matrix,The Matrix,136,136,"[Action, Adventure, Sci-Fi]"
tt1375666,Inception (2010),2010,8.9,385149,148 mins.,Action|Adventure|Sci-Fi|Thriller,Inception,Inception,148,148,"[Action, Adventure, Sci-Fi, Thriller]"
...,...,...,...,...,...,...,...,...,...,...,...
tt0807721,Meduzot (2007),2007,7.0,1357,78 mins.,Drama,Meduzot,Meduzot,78,78,[Drama]
tt0339642,Daltry Calhoun (2005),2005,5.2,1357,100 mins.,Comedy|Drama|Music|Romance,Daltry Calhoun,Daltry Calhoun,100,100,"[Comedy, Drama, Music, Romance]"
tt0060880,The Quiller Memorandum (1966),1966,6.5,1356,104 mins.,Drama|Mystery|Thriller,The Quiller Memorandum,The Quiller Memorandum,104,104,"[Drama, Mystery, Thriller]"
tt0152836,Taal (1999),1999,6.5,1356,179 mins.,Musical|Romance,Taal,Taal,179,179,"[Musical, Romance]"
tt0279977,The Navigators (2001),2001,6.9,1356,96 mins.,Comedy|Drama,The Navigators,The Navigators,96,96,"[Comedy, Drama]"